'use client';
import { useMemo, useState } from 'react';

type Intel={id:number;category:string;title:string;summary:string;date:string;source:string;url?:string;verified:boolean;tag:string;audience:string;opportunity:string;product:string;explain:string;script:string;social:string};
const data:Intel[]=[
{id:1,category:'行业情报',title:'建筑节能改造被纳入城市设备更新重点',summary:'既有建筑节能改造被列为建筑和市政基础设施设备更新的重点任务之一。',date:'2024-04-17',source:'国家发展改革委转载·住建部通知',url:'https://www.ndrc.gov.cn/xwdt/ztzl/tddgmsbgxhxfpyjhx/gzdt/202404/t20240417_1365729.html',verified:true,tag:'政策机会',audience:'老旧小区业主、物业、工程客户',opportunity:'以“整窗节能升级”切入旧窗改造需求，重点诊断漏风、结露与冬冷夏热。',product:'断桥铝系统窗＋Low-E中空玻璃＋多道密封',explain:'政策说的是建筑节能改造，并不等于所有换窗都能拿补贴；先确认当地细则，再用检测与能耗问题做方案。',script:'您家如果有漏风、结露或空调能耗高的问题，建议先做一次窗体诊断。我们会按洞口、朝向和楼层给出整窗配置，不把政策概念当成补贴承诺。',social:'旧窗改造不只是“换一扇新窗”，更重要的是把型材、玻璃、密封和安装做成一套节能系统。政策方向值得关注，具体补贴以当地官方细则为准。'},
{id:2,category:'行业情报',title:'家装厨卫“焕新”政策曾覆盖门窗品类',summary:'部分地区2024年家装厨卫焕新细则将门窗纳入支持范围，地域、时段和标准各不相同。',date:'2024-09-14',source:'甘肃省商务厅实施细则',url:'https://swt.gansu.gov.cn/swt/c116362/202409/173981115/files/3e4908d33138421983ccb9ee17d24143.pdf',verified:true,tag:'以旧换新',audience:'近期装修、旧房翻新客户',opportunity:'用“先查当地政策、再测量报价”的方式获取高意向旧改线索。',product:'旧窗焕新套餐＋拆旧、防水、收口一体化服务',explain:'这类补贴具有明显地域和有效期差异，销售时必须让客户查询当前属地官方平台。',script:'门窗在部分地区曾进入家装焕新品类，但政策会随地区和时间变化。我先帮您核对当地最新规则，再按实际洞口给您做透明报价。',social:'准备换窗的朋友，别只问“有没有补贴”。先核对所在地最新细则，再看产品配置、安装交付和售后是否真正适合自家。'},
{id:3,category:'产品知识',title:'门窗“三性”检测应看现行方法标准',summary:'GB/T 7106—2019规定建筑外门窗气密、水密、抗风压性能的检测方法。',date:'2019-12-10',source:'全国标准信息公共服务平台',url:'https://std.samr.gov.cn/gb/search/gbDetailed?id=996A838ABF808372E05397BE0A0AD949',verified:true,tag:'性能标准',audience:'高层、沿海、强风雨地区客户',opportunity:'把“型材厚不厚”升级为整窗性能与适用场景的专业沟通。',product:'有对应整窗检测报告的系统窗方案',explain:'三项性能是整窗系统结果，不能只凭某个材料参数推断；报告还要核对规格、开启方式与送检样品。',script:'您家在高层，建议重点看整窗的气密、水密和抗风压检测依据，而不是只比较型材宽度。我们可以把报告与您家的窗型、尺寸逐项对应。',social:'选高层门窗，别只盯“几腔体、几道密封”。整窗三性、窗型尺寸和安装节点，才是一起决定安全与舒适度的关键。'},
{id:4,category:'产品知识',title:'保温性能同时关注传热系数与抗结露因子',summary:'现行GB/T 8484—2020规定建筑外门窗保温性能的检测方法。',date:'2020-04-28',source:'全国标准信息公共服务平台',url:'https://std.samr.gov.cn/gb/search/gbDetailed?id=A47A713B760814ABE05397BE0A0ABB25',verified:true,tag:'保温节能',audience:'北方采暖区、空调房、易结露家庭',opportunity:'从单一玻璃配置拓展到边部、型材、密封与安装热桥的系统方案。',product:'低传热整窗＋暖边中空玻璃＋保温收口',explain:'保温不是只看玻璃层数，整窗构造、边部和安装节点都会影响最终表现。',script:'如果您冬天窗边发冷或结露，我们会同时看玻璃、窗框、边部和安装位置，目标是降低整窗传热并减少结露风险。',social:'同样是“双玻”，体感可能差很多。窗框、玻璃、暖边、密封和安装热桥要一起看，才是真正的保温系统。'},
{id:5,category:'产品知识',title:'隔音性能应以整窗空气声隔声检测为依据',summary:'现行GB/T 8485—2008规定建筑门窗空气声隔声性能的分级及检测方法。',date:'2008-07-30',source:'全国标准信息公共服务平台',url:'https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D7FF5DD3A7E05397BE0A0AB82A',verified:true,tag:'临街隔音',audience:'临街、机场、高架与广场舞噪声客户',opportunity:'先识别噪声类型，再匹配玻璃组合、开启方式与密封方案。',product:'按噪声频段配置的夹胶/中空组合系统窗',explain:'不能用单片玻璃参数代替整窗隔声效果，现场噪声源和安装缝隙同样重要。',script:'隔音不能只问“几层玻璃”。我先了解是车流低频、鸣笛还是人声，再结合整窗检测与安装密封给您选配置。',social:'临街换窗的正确顺序：先听噪声类型，再看整窗隔声，再定玻璃组合，最后盯住安装密封。不是玻璃越多就一定越安静。'},
{id:6,category:'行业情报',title:'“好房子”实用技术征集聚焦隔音、渗漏等痛点',summary:'住建部门征集能解决隔音不好、渗漏等问题的技术产品，并强调安全、舒适、绿色、智慧。',date:'2025-05-20',source:'住房城乡建设部标准定额司通知（政府网站转载）',url:'https://www.huining.gov.cn/xxgk/xzxxgk/hsz/fdzdgknr/zfbz/art/2025/art_942e60d610544a7ca355f459a13bd25d.html',verified:true,tag:'好房子',audience:'改善型住房、品质住宅与设计师渠道',opportunity:'从“卖材料”转向“舒适居住解决方案”，连接采光、通风、隔音、保温与安全。',product:'场景化系统门窗解决方案',explain:'“好房子”是建设导向，具体项目仍须以当地规范、设计文件和检测要求为准。',script:'好窗不是参数堆砌，而是针对您家的朝向、噪声、风雨和使用习惯，把安全、安静、保温与通风平衡好。',social:'“好房子”先要有好围护。门窗连接室内外，安全、隔音、保温、通风与采光，缺一项都可能影响日常体验。'},
{id:7,category:'销售话术',title:'客户说“你家比别人贵”怎么回应',summary:'用同口径配置清单拆解价格，而不是立即打折。',date:'2026-08-26',source:'平台演示内容',verified:false,tag:'异议处理',audience:'多品牌比价客户',opportunity:'把价格争议转换为配置、交付和风险的可比项。',product:'同需求、同规格的分级报价方案',explain:'先确认客户在比较哪些项目，再逐项对齐型材、玻璃、五金、安装与售后。',script:'价格差异我理解。咱们先把窗型尺寸、玻璃、五金、安装和售后五项对齐；如果配置同等，我们再看哪里还能为您优化预算。',social:'买窗最怕“总价看着便宜，细项说不清”。真正可比的报价，必须把玻璃、五金、开启扇、安装和售后写明白。'},
{id:8,category:'销售话术',title:'客户担心断桥铝都是智商税',summary:'不争辩材料名词，回到热传递路径与整窗证据。',date:'2026-08-26',source:'平台演示内容',verified:false,tag:'价值沟通',audience:'对参数宣传反感的理性客户',opportunity:'用结构样角、整窗报告和场景需求建立信任。',product:'配置透明、报告可核验的断桥铝系统窗',explain:'隔热条只是系统的一部分，不能单独承诺整窗节能效果。',script:'您这个担心很合理。断桥结构有没有价值，不能只听名字，要看整窗传热、玻璃、密封和安装是否匹配。我把样角和报告一起给您看。',social:'材料名词不等于使用效果。看门窗，最终要落到整窗数据、真实配置和安装交付。'},
{id:9,category:'竞品情报',title:'竞品推出“超窄边框全景窗”新品',summary:'用于演示新品监测卡片，不对应任何真实品牌或发布事件。',date:'2026-08-20',source:'平台演示内容',verified:false,tag:'新品监测',audience:'重视颜值与采光的年轻客群',opportunity:'比较可视面、玻璃面积、安全余量和维护便利性。',product:'窄边框景观窗方案',explain:'新品比较应核对结构、尺寸限制和检测证据，不能只比可视面。',script:'如果您喜欢窄边框，我们可以同时比较视野、最大尺寸、安全性和后期维护，选一个颜值与性能都平衡的方案。',social:'窄边框的高级感来自比例，也来自结构克制。颜值要看，尺寸边界、安全和长期维护更要看。'},
{id:10,category:'案例库',title:'临街卧室：夜间车流噪声改造思路',summary:'演示案例：通过噪声识别、窗型调整与密封安装制定方案。',date:'2026-08-18',source:'平台演示案例',verified:false,tag:'临街隔音',audience:'主干道、高架沿线家庭',opportunity:'以现场勘测和分级方案替代“一口价隔音窗”。',product:'内开系统窗＋针对性玻璃组合＋高气密安装',explain:'演示案例不代表实际降噪数值，最终效果取决于现场噪声、墙体和施工。',script:'我先在白天和晚高峰分别了解噪声，再判断主要是低频车流还是突发鸣笛，之后给您两档玻璃与窗型方案。',social:'隔音改造先“诊断”，再“开方”。噪声来源、窗墙比例、开启方式和安装缝隙，都会影响最终体感。'},
{id:11,category:'案例库',title:'高层转角窗：强风雨场景配置思路',summary:'演示案例：围绕楼层、朝向、洞口尺寸和开启扇规划抗风雨方案。',date:'2026-08-15',source:'平台演示案例',verified:false,tag:'高层抗风',audience:'高层、转角、沿海住宅',opportunity:'用结构复核、窗型优化和安装节点提升客单价值。',product:'加强型系统窗＋可靠五金＋防水安装节点',explain:'演示方案不能代替项目结构计算或当地设计要求。',script:'高层窗不能只看壁厚。我需要先确认楼层、朝向、洞口和开启扇尺寸，再结合整窗报告与安装节点做配置。',social:'高层选窗，窗型设计往往比“堆参数”更重要。合理分格、可靠五金、整窗性能和安装节点必须一起落地。'},
{id:12,category:'营销素材',title:'朋友圈：为什么报价前要先量窗',summary:'可直接复制的旧窗改造科普文案。',date:'2026-08-26',source:'平台演示内容',verified:false,tag:'朋友圈',audience:'旧房换窗潜客',opportunity:'引导客户预约上门勘测。',product:'免费初勘＋分级配置建议',explain:'避免在未知尺寸、墙体和施工条件时承诺固定价格。',script:'方便的话我先上门看一下洞口、墙体和漏风漏水位置，量完再给您做两档配置，预算会更准确。',social:'换窗报价为什么不能只报“多少钱一平方”？因为开启方式、玻璃、五金、拆旧、防水和收口都会影响最终方案。先量窗，再报价，才是对结果负责。'},
{id:13,category:'营销素材',title:'短视频选题：三分钟看懂门窗密封',summary:'演示选题：用纸片测试、密封结构和错误安装做对比。',date:'2026-08-25',source:'平台演示内容',verified:false,tag:'短视频',audience:'重视漏风、灰尘与噪声的家庭',opportunity:'用可视化测试引导到店体验。',product:'多道密封系统窗',explain:'纸片测试只适合做直观演示，不能代替标准检测。',script:'您可以来店里做一个直观密封体验，我再结合整窗气密检测依据，解释哪些结构真正影响漏风。',social:'一张纸能不能测出窗户密封？它只能做直观体验，真正判断还要看整窗气密、结构连续性和安装缝隙。'},
{id:14,category:'产品知识',title:'安装发泡剂不是窗边防水的全部',summary:'演示知识：窗框固定、缝隙填充、防水密封与收口应形成完整节点。',date:'2026-08-22',source:'平台演示内容',verified:false,tag:'安装工艺',audience:'旧窗改造、渗水发霉客户',opportunity:'把隐蔽安装工艺变成可展示、可验收的服务价值。',product:'标准化安装交付包',explain:'具体节点需按墙体、外饰面与当地工程要求设计。',script:'安装不是打一圈发泡剂就结束。我们会把固定、填缝、内外密封和收口分别说明，并在隐蔽前留存照片。',social:'三分产品，七分安装不是口号。固定、防水、填缝、密封、收口，每一步都应该看得见、说得清、能验收。'}];
const nav=['首页','行业情报','产品知识','销售话术','竞品情报','案例库','营销素材'];
export default function Home(){const[page,setPage]=useState('首页');const[query,setQuery]=useState('');const[filter,setFilter]=useState('全部');const[selected,setSelected]=useState<Intel|null>(null);const[copied,setCopied]=useState('');const tags=['全部',...Array.from(new Set(data.map(i=>i.tag)))];const shown=useMemo(()=>data.filter(i=>(page==='首页'||i.category===page)&&(filter==='全部'||i.tag===filter)&&(`${i.title}${i.summary}${i.audience}`.includes(query))),[page,filter,query]);const copy=async(text:string,key:string)=>{await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(''),1400)};return <main>
<header className="topbar"><button className="brand" onClick={()=>setPage('首页')}><span className="brandmark">W</span><span><b>窗见</b><small>销售情报台</small></span></button><nav>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setFilter('全部')}}>{n}</button>)}</nav><button className="briefBtn" onClick={()=>setPage('营销素材')}>生成今日素材 <span>↗</span></button></header>
<section className="hero"><div className="eyebrow"><span/>门窗业务员的每日决策入口</div><h1>{page==='首页'?'把行业资讯，变成今天能用的销售行动':page}</h1><p>{page==='首页'?'政策、产品、竞品与客户问题，已经替你拆解成机会、方案和可复制话术。':`已为你整理 ${shown.length} 条可直接用于销售沟通的内容。`}</p><div className="search"><span>⌕</span><input aria-label="搜索情报" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索政策、隔音、高层、异议处理…"/><kbd>搜索</kbd></div><div className="metrics"><div><strong>14</strong><span>条首版情报</span></div><i/><div><strong>6</strong><span>条来源核验</span></div><i/><div><strong>7</strong><span>个业务场景</span></div><i/><div><strong>100%</strong><span>可转销售话术</span></div></div></section>
<section className="workspace"><div className="sectionHead"><div><span className="kicker">INTELLIGENCE FEED</span><h2>{page==='首页'?'今日重点情报':page+'内容库'}</h2></div><span className="updated">● 内容更新至 2026.08.26</span></div><div className="chips">{tags.map(t=><button key={t} className={filter===t?'on':''} onClick={()=>setFilter(t)}>{t}</button>)}</div><div className="grid">{shown.map(item=><article className="card" key={item.id}><div className="cardTop"><span className={item.verified?'status verified':'status sample'}>{item.verified?'✓ 已核验':'演示示例'}</span><span className="date">{item.date}</span></div><span className="tag">{item.tag}</span><h3>{item.title}</h3><p className="summary">{item.summary}</p><div className="opportunity"><b>销售机会</b><p>{item.opportunity}</p></div><div className="audience"><span>影响客户</span>{item.audience}</div><div className="cardFoot"><button onClick={()=>setSelected(item)}>查看销售拆解 <span>→</span></button><button className="copy" onClick={()=>copy(item.script,'card'+item.id)}>{copied==='card'+item.id?'已复制':'复制话术'}</button></div></article>)}</div>{!shown.length&&<div className="empty">没有找到相关内容，换个关键词试试。</div>}</section>
<section className="notice"><b>内容边界说明</b><p>带“已核验”的内容来自公开官方渠道；带“演示示例”的内容仅用于展示产品形态，不对应真实政策、价格、品牌发布或检测结论。成交前请复核属地政策、项目条件与原始检测报告。</p></section>
{selected&&<div className="modalBackdrop" onMouseDown={()=>setSelected(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modalMeta"><span className={selected.verified?'status verified':'status sample'}>{selected.verified?'✓ 已核验':'演示示例'}</span><span>{selected.date}</span></div><h2>{selected.title}</h2><p className="lead">{selected.summary}</p><dl><div><dt>信息来源</dt><dd>{selected.url?<a href={selected.url} target="_blank">{selected.source} ↗</a>:selected.source}</dd></div><div><dt>影响客户</dt><dd>{selected.audience}</dd></div><div className="orange"><dt>销售机会</dt><dd>{selected.opportunity}</dd></div><div><dt>建议产品</dt><dd>{selected.product}</dd></div><div><dt>应该怎么讲</dt><dd>{selected.explain}</dd></div></dl><div className="copyBox"><div><b>客户话术</b><button onClick={()=>copy(selected.script,'script')}>{copied==='script'?'已复制 ✓':'一键复制'}</button></div><p>{selected.script}</p></div><div className="copyBox social"><div><b>朋友圈文案</b><button onClick={()=>copy(selected.social,'social')}>{copied==='social'?'已复制 ✓':'一键复制'}</button></div><p>{selected.social}</p></div></section></div>}
</main>}

